---
# tasks for tivoli backup client
#

- name: create rpm temp dir
  file:
    path: '{{ rpmdir }}'
    state: directory
    mode: '0755'
  tags:
  - tivoliba

- name: copy rpms tivoli backup client
  copy:
    src: '{{ item }}'
    dest: '{{ rpmdir }}'
  with_fileglob:
    - rpms/*.rpm
  tags:
  - tivoliba

- name: Find tivoli RPM files
  find:
    paths: '{{ rpmdir }}'
    patterns: "*.rpm"
  register: rpm_result
  tags:
  - tivoliba

- name: install tivoli rpms
  yum:
    name: "{{ item.path }}"
    state: present
  with_items: "{{ rpm_result.files }}"
  retries: 5
  register: result
  until: result.rc == 0
  tags:
  - tivoliba

- name: create tivoli logdir
  file:
    path: '{{ tivoli_logdir }}'
    state: directory
    mode: '0755'
  tags:
  - tivoliba

- name: create adsm configdir
  file:
    path: '{{ adsm_cfgdir }}'
    state: directory
    mode: '0755'
  tags:
  - tivoliba

- name: copy tivoli config
  template:
    src: dsm.sys.j2
    dest: '{{ tivoli_cfgdir }}/dsm.sys'
    mode: 0644
    owner: root
    group: root
    force: yes
  notify: restart dsmcad
  tags:
  - tivoliba
  ignore_errors: yes

- name: copy tivoli include exclude files
  copy:
    src: '{{ item }}'
    dest: '{{ tivoli_cfgdir }}/{{ item }}'
    mode: 0644
    owner: root
    group: root
    force: yes
  with_items:
    - dsm.inclexcl-etc
    - dsm.opt-etc
  notify: restart dsmcad
  tags:
  - tivoliba

- name: link tivoli cfg files
  file:
    src: '{{ tivoli_cfgdir }}/{{ item }}'
    dest: '{{ adsm_cfgdir }}/{{ item }}'
    state: link
  with_items:
    - dsm.inclexcl-etc
    - dsm.opt-etc
  tags:
  - tivoliba
  ignore_errors: yes

- name: copy systemd file
  template:
    src: dsmcad.service.j2
    dest: /etc/systemd/system/dsmcad.service
    mode: 0755
    owner: root
    group: root
  tags:
  - tivoliba

- name: start and enable dsmcad
  service:
    name: dsmcad
    state: started
    enabled: true
    daemon_reload: yes
  tags:
  - tivoliba
